# Setup
title:        Understanding Neural Nets Forwards and Backwards
tagline:      A Walk-Through of how Neural Nets Work from the Forward Pass to Backpropagation 
baseurl:      ""
paginate:     1

# About/contact
author:  
  name:       Benjamin S. Knight
  url:        https://b-knight.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown